name: Frontend CI

on:
  push:
    paths:
      - 'wato-frontend/**' # Trigger only when changes occur within wato-frontend directory
  pull_request:
    paths:
      - 'wato-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: wato-frontend

      - name: Lint
        run: npm run lint
        working-directory: wato-frontend

      - name: Build
        run: npm run build --prod
        working-directory: wato-frontend

      - name: Test
        run: npm run test
        working-directory: wato-frontend

      - name: Archive test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: wato-frontend/coverage/

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: wato-frontend/dist/
